### ISSUE TITLE
pyats testbed issue

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/virl2-client#133]
With pyats 25.1 installed, when running the run_command function, warnings are getting generated.
Example code:
```
from virl2_client import ClientLibrary
from virl2_client.models.cl_pyats import ClPyats

cml_ip = ...
cml_username = ...
cml_password = ...

node_label = "edge"

cml = ClientLibrary(cml_ip, cml_username, cml_password, ssl_verify=False)

lab = cml.find_labs_by_title("pyatstest")[0]
pylab = ClPyats(lab)
pylab.sync_testbed(cml_username, cml_password)
pylab._testbed.devices[node_label].credentials.default.username = "admin"
pylab._testbed.devices[node_label].credentials.default.password = "admin"

running_config = pylab.run_command(node_label, "show sdwan run")
print(running_config)
```

The following code generates warnings:
```
Could not find details in testbed for server terminal_server.
Could not find details in testbed for server terminal_server.
No details found in testbed for hostname terminal_server.
Could not find details in testbed for server terminal_server.
Could not find details in testbed for server terminal_server.
No details found in testbed for hostname terminal_server.
```

I assume there's something wrong with the testbed object that virl2_client generates. Ask is to fix it so no warnings are generated on run_command function.

**Comment by sgherdao** [comment]
```yaml
testbed:
  name: TESTBED
  servers:                           <<
    terminal_server:           <<
      type: server                <<
devices:
  terminal_server:
    os: linux
    type: server 
```

I found adding `servers` under `testbed` make the warnings go away
